"""empty message

Revision ID: 00c5ec26b8e7
Revises: 88216505fb2a
Create Date: 2016-11-01 12:06:17.340952

"""

# revision identifiers, used by Alembic.
revision = '00c5ec26b8e7'
down_revision = '88216505fb2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('passhash', sa.String(length=120), nullable=True),
    sa.Column('pi_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('passhash'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('pi_id')
    )
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_picture', sa.Boolean(), nullable=True),
    sa.Column('request_log', sa.Boolean(), nullable=True),
    sa.Column('request_update_settings', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=120), nullable=True),
    sa.Column('capture_framerate', sa.Integer(), nullable=True),
    sa.Column('output_framerate', sa.Integer(), nullable=True),
    sa.Column('threshold_frame_count', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('s3_video_url', sa.String(length=120), nullable=True),
    sa.Column('s3_gif_url', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('pi')
    op.drop_table('flags')
    op.drop_table('users')
    ### end Alembic commands ###
