"""empty message

Revision ID: 4e485d1a1412
Revises: e5e298af84d3
Create Date: 2016-10-30 15:16:37.095422

"""

# revision identifiers, used by Alembic.
revision = '4e485d1a1412'
down_revision = 'e5e298af84d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('s3_gif_url', sa.String(length=120), nullable=True))
    op.add_column('video', sa.Column('s3_video_url', sa.String(length=120), nullable=True))
    op.drop_column('video', 's3_url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('s3_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('video', 's3_video_url')
    op.drop_column('video', 's3_gif_url')
    ### end Alembic commands ###
