"""empty message

Revision ID: 4f397dedef38
Revises: ce4f631d7561
Create Date: 2016-10-27 17:18:26.025533

"""

# revision identifiers, used by Alembic.
revision = '4f397dedef38'
down_revision = 'ce4f631d7561'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'passhash',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.alter_column('user', 'pi_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('video', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('video', 's3_url',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('video', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('video', 's3_url',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('video', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'pi_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('user', 'passhash',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    ### end Alembic commands ###
