"""empty message

Revision ID: 5f7d5442bfb5
Revises: None
Create Date: 2016-10-30 17:58:24.422000

"""

# revision identifiers, used by Alembic.
revision = '5f7d5442bfb5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_name', sa.String(length=120), nullable=True),
    sa.Column('capture_framerate', sa.Integer(), nullable=True),
    sa.Column('output_framerate', sa.Integer(), nullable=True),
    sa.Column('threshold_frame_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pi')
    ### end Alembic commands ###
