"""empty message

Revision ID: 88216505fb2a
Revises: 5f7d5442bfb5
Create Date: 2016-10-30 18:15:02.632508

"""

# revision identifiers, used by Alembic.
revision = '88216505fb2a'
down_revision = '5f7d5442bfb5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_picture', sa.Boolean(), nullable=True),
    sa.Column('request_log', sa.Boolean(), nullable=True),
    sa.Column('request_update_settings', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flags')
    ### end Alembic commands ###
