"""empty message

Revision ID: ce4f631d7561
Revises: None
Create Date: 2016-10-27 17:12:12.866709

"""

# revision identifiers, used by Alembic.
revision = 'ce4f631d7561'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('passhash', sa.String(length=120), nullable=False),
    sa.Column('pi_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('passhash'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('pi_id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('s3_url', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video')
    op.drop_table('user')
    ### end Alembic commands ###
