"""empty message

Revision ID: ced7e9c6b5ec
Revises: None
Create Date: 2016-10-11 17:58:48.758279

"""

# revision identifiers, used by Alembic.
revision = 'ced7e9c6b5ec'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('passhash', sa.String(length=120), nullable=True),
    sa.Column('pi_id', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('passhash'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('pi_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
